dist: trusty
sudo: required
language: java
jdk:
  - openjdk7
  #- oraclejdk8 moved to jobs section, see below
  - openjdk8
  #- oraclejdk9 jacoco does not work
  #- openjdk9 not available for Trusty
env:
  - CONTAINER=hibernate
  - CONTAINER=eclipselink
  - CONTAINER=openjpa
install: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline -B -V -P $CONTAINER
script: mvn clean test -B -P $CONTAINER
cache:
    directories:
        - $HOME/.m2
addons:
  sonarcloud:
    organization: "ok"
jobs:
  include:
    - jdk: oraclejdk8
      env:
        - CONTAINER=hibernate
      script:
        # internal pull request
        - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then mvn test -B -P $CONTAINER sonar:sonar ; fi'
        # external pull request via fork
        # TODO fix it
        # - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then mvn test -B -P $CONTAINER sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ok; fi'
        - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then mvn test -B -P $CONTAINER; fi'
    - jdk: oraclejdk8
      env:
        - CONTAINER=eclipselink
      script: mvn test -B -P $CONTAINER
    - jdk: oraclejdk8
      env:
        - CONTAINER=openjpa
      script: mvn test -B -P $CONTAINER
