/* Generated By:JJTree: Do not edit this line. JpqlParserVisitor.java
 * Copyright 2008 Arne Limburg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 */

package net.sf.jpasecurity.jpql.parser;

/**
 * This class is to be implemented by objects that want to visit a JPQL-tree.
 * @author Arne Limburg
 */
public interface JpqlParserVisitor {

    boolean visit(Node node, int nextChildIndex);
    
    /**
     * Called when visiting a <tt>JpqlStatement</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlStatement node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSelect</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSelect node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlUpdate</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlUpdate node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDelete</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDelete node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlFrom</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlFrom node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlFromItem</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlFromItem node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIdentificationVariableDeclaration</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIdentificationVariableDeclaration node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlInnerJoin</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlInnerJoin node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlOuterJoin</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlOuterJoin node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlOuterFetchJoin</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlOuterFetchJoin node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlInnerFetchJoin</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlInnerFetchJoin node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlPath</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlPath node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlUpdateItem</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlUpdateItem node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlUpdateValue</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlUpdateValue node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSelectClause</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSelectClause node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSelectExpressions</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSelectExpressions node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSelectExpression</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSelectExpression node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlConstructor</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlConstructor node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlClassName</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlClassName node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlConstructorParameter</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlConstructorParameter node, int nextChildIndex);

    /**
     * Called when visiting a query-part in brackets.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlBrackets node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDistinct</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDistinct node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDistinctPath</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDistinctPath node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlCount</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlCount node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAverage</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAverage node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlMaximum</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlMaximum node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlMinimum</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlMinimum node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSum</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSum node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlWhere</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlWhere node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlGroupBy</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlGroupBy node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlHaving</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlHaving node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSubselect</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSubselect node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlOr</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlOr node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAnd</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAnd node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlNot</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlNot node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlBetween</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlBetween node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIn</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIn node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlLike</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlLike node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIsNull</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIsNull node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIsEmpty</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIsEmpty node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlMemberOf</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlMemberOf node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlExists</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlExists node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAny</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAny node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAll</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAll node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlEquals</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlEquals node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlNotEquals</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlNotEquals node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlGreaterThan</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlGreaterThan node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlGreaterOrEquals</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlGreaterOrEquals node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlLessThan</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlLessThan node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlLessOrEquals</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlLessOrEquals node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAdd</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAdd node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSubtract</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSubtract node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlMultiply</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlMultiply node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDivide</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDivide node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlNegative</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlNegative node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlConcat</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlConcat node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSubstring</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSubstring node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlTrim</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlTrim node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlLower</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlLower node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlUpper</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlUpper node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlTrimLeading</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlTrimLeading node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlTrimTrailing</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlTrimTrailing node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlTrimBoth</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlTrimBoth node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlLength</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlLength node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAbs</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAbs node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSqrt</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSqrt node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlMod</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlMod node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlSize</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlSize node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlCurrentDate</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlCurrentDate node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlCurrentTime</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlCurrentTime node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlCurrentTimestamp</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlCurrentTimestamp node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlOrderBy</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlOrderBy node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlOrderByItem</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlOrderByItem node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAscending</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAscending node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDescending</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDescending node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlAbstractSchemaName</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlAbstractSchemaName node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIdentifier</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIdentifier node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIdentificationVariable</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIdentificationVariable node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlIntegerLiteral</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlIntegerLiteral node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlDecimalLiteral</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlDecimalLiteral node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlBooleanLiteral</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlBooleanLiteral node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlStringLiteral</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlStringLiteral node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlNamedInputParameter</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlNamedInputParameter node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlPositionalInputParameter</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlPositionalInputParameter node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlPatternValue</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlPatternValue node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlEscapeCharacter</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlEscapeCharacter node, int nextChildIndex);

    /**
     * Called when visiting a <tt>JpqlTrimCharacter</tt> node.
     * @param node the current node
     * @param nextChildIndex the index of the next child to process
     * @return <tt>true</tt>, if the node should go on processing the children
     */
    boolean visit(JpqlTrimCharacter node, int nextChildIndex);
}
